services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://key.${DOMAIN}" # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account so that no strangers can register
      #DISABLE_ADMIN_TOKEN: true
    volumes:
      - ${VAULTWARDEN_DATA}:/data # the path before the : can be changed
    # ports:
    #   - 11001:80 # you can replace the 11001 with your preferred port
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`key.${DOMAIN}`)
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.http.routers.vaultwarden-admin.rule: (Host(`key.${DOMAIN}`)) && Path(`/admin`)
      traefik.http.routers.vaultwarden-admin.middlewares: domain-authentik
      traefik.http.routers.vaultwarden-admin.priority: 100
    networks:
      - traefik
networks:
  traefik:
    external: true
