services:
  v2raya:
    image: mzz2017/v2raya
    restart: unless-stopped
    privileged: true
    environment:
      V2RAYA_LOG_FILE: /tmp/v2raya.log
      V2RAYA_V2RAY_BIN: /usr/local/bin/v2ray
      V2RAYA_NFTABLES_SUPPORT: off
      IPTABLES_MODE: legacy
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ${DATA_BASE}/v2raya:/etc/v2raya
    ports:
      - 20170-20180:20170-20180
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.v2raya.rule=Host(`v2raya.${DOMAIN}`)"
      - "traefik.http.routers.v2raya.service=v2raya"
      - "traefik.http.services.v2raya.loadbalancer.server.port=2017"
    networks:
      - traefik
