log:
  level: INFO
api:
  insecure: true
  dashboard: true
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        options: default
    transport:
      respondingTimeouts:
        readTimeout: 0
        writeTimeout: 0
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/traefik.crt"
        keyFile: "/etc/traefik/traefik.key"
  certificates:
    - certFile: "/etc/traefik/traefik.crt"
      keyFile: "/etc/traefik/traefik.key"
      stores:
        - default
providers:
  docker:
    network: traefik
  file:
    filename: /etc/traefik/traefik.yaml
