#https://raw.githubusercontent.com/P3TERX/Aria2-Pro-Docker/master/docker-compose.yml
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - UMASK_SET=022
      - RPC_SECRET=${ARIA2_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${ARIA2_CONFIG_PATH}:/config
      - ${ARIA2_DOWNLOADS_PATH}:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: always
    # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2rpc.rule=Host(`aria2.${DOMAIN}`) && Path(`/jsonrpc`)"
      - "traefik.http.routers.aria2rpc.service=aria2rpc"
      - "traefik.http.services.aria2rpc.loadbalancer.server.port=6800"
      - "traefik.http.routers.aria2rpc.middlewares=domain-authentik"
    networks:
      - traefik
  # AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    environment:
      - PUID=1000
      - PGID=1000
      - ARIA2RPCPORT=443
      - RPC_SECRET=${ARIA2_SECRET}
    command: --port 6880 --ipv6
    # ports:
    #   - 6880:6880
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aria2.rule=Host(`aria2.${DOMAIN}`)"
      - "traefik.http.routers.aria2.service=aria2"
      - "traefik.http.services.aria2.loadbalancer.server.port=6880"
      - "traefik.http.routers.aria2.middlewares=domain-authentik"
    networks:
      - traefik
networks:
  traefik:
    external: true
